eureka:
  instance:
    hostname: ms-discovery-server
  client:
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false