spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:

        - id: book-service
          uri: http://ms-book-service:8010
          predicates:
            - Path=/api/v1/books/**

        - id: member-service
          uri: http://ms-member-service:8020
          predicates:
            - Path=/api/v1/members/**

        - id: rent-service
          uri: http://ms-rent-service:8030
          predicates:
            - Path=/api/v1/rents/**

server:
  port: 8222