spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rents
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8030

application:
  config:
    books-url: http://localhost:8222/api/v1/books
    members-url: http://localhost:8222/api/v1/members